name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "gump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
